import "./globals.css";
import Header from "@/components/Header"
import Nav from "@/components/Nav";
import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: ['100','300','400','500','700','900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
      <div className="h-screen w-full items-center justify-center flex flex-col text-center">
        <Header />
        {children}
      </div>
      </body>
    </html>
  );
}
